Region: eu-west-2
Image:
  Os: alinux2

HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: HEAD_NODE_SUBNET_PLACEHOLDER
  Ssh:
    KeyName: parallelcluster-ssh-key
  Iam:
    S3Access:
      - BucketName: openfoam-cluster-bootstrap-ACCOUNT_ID_PLACEHOLDER
        EnableWriteAccess: false
  CustomActions:
    OnNodeConfigured:
      Script: s3://openfoam-cluster-bootstrap-ACCOUNT_ID_PLACEHOLDER/install-singularity.sh

Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: compute
      Iam:
        S3Access:
          - BucketName: openfoam-cluster-bootstrap-ACCOUNT_ID_PLACEHOLDER
            EnableWriteAccess: false
      CustomActions:
        OnNodeConfigured:
          Script: s3://openfoam-cluster-bootstrap-ACCOUNT_ID_PLACEHOLDER/install-singularity.sh
      ComputeResources:
        - Name: cfd-nodes
          Instances:
            - InstanceType: c5n.4xlarge
          MinCount: 0
          MaxCount: 8
      Networking:
        SubnetIds:
          - subnet-08e52a4a07c191043
          - subnet-0ffc53a53aefc485c
          - subnet-0ca2ccbb238c41833

SharedStorage:
  - MountDir: /shared
    Name: shared-storage
    StorageType: Efs
    EfsSettings:
      DeletionPolicy: Delete